### ISSUE TITLE
Gradle Plugin

### ISSUE THREAD

**Issue by sirinath** [Concurnas/Concurnas#58]
Can a Gradle plugin be developed so we can use this in with Gradle? Mostly they would be mixed projects with code already in other JVM languages.

**Comment by jasontatton** [comment]
Though as you point out there isn't an 'official' gradle plugin for Concurnas right now, there is the following produced by @DeflatedPickle: https://plugins.gradle.org/plugin/com.deflatedpickle.gradle.concurnas (https://github.com/DeflatedPickle/gradle-concurnas). FYI: I have not had an opportunity to use it yet.

**Comment by DeflatedPickle** [comment]
It exists and is published, but I believe there was a change to how source sets work, as the plugin no longer works due to the custom source set (or I wrote it for a deprecated Gradle version?).

This is a problem I'm not sure how to fix and keep forgetting to ask about on the Gradle forums. Sorry about that.
